# Generated by Django 5.2.1 on 2025-09-27 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CVSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200, verbose_name='Nombre Completo')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('posicion_interes', models.CharField(choices=[('agente_inmobiliario', 'Agente Inmobiliario'), ('asesor_comercial', 'Asesor Comercial'), ('gerente_ventas', 'Gerente de Ventas'), ('administrativo', 'Personal Administrativo'), ('marketing', 'Especialista en Marketing'), ('contabilidad', 'Contabilidad'), ('legal', 'Asesoría Legal'), ('otro', 'Otra posición')], max_length=50, verbose_name='Posición de Interés')),
                ('anos_experiencia', models.CharField(blank=True, choices=[('sin_experiencia', 'Sin experiencia'), ('1-2', '1-2 años'), ('3-5', '3-5 años'), ('6-10', '6-10 años'), ('10+', 'Más de 10 años')], max_length=20, null=True, verbose_name='Años de Experiencia')),
                ('nivel_educativo', models.CharField(blank=True, choices=[('secundario', 'Secundario Completo'), ('terciario', 'Terciario'), ('universitario', 'Universitario'), ('posgrado', 'Posgrado')], max_length=20, null=True, verbose_name='Nivel Educativo')),
                ('cv_file', models.FileField(help_text='Formatos aceptados: PDF, DOC, DOCX', upload_to='cvs/%Y/%m/%d/', verbose_name='Archivo CV')),
                ('carta_presentacion', models.TextField(blank=True, null=True, verbose_name='Carta de Presentación')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Envío')),
                ('procesado', models.BooleanField(default=False, verbose_name='Procesado')),
                ('notas_admin', models.TextField(blank=True, null=True, verbose_name='Notas del Administrador')),
            ],
            options={
                'verbose_name': 'CV Enviado',
                'verbose_name_plural': 'CVs Enviados',
                'ordering': ['-fecha_envio'],
            },
        ),
    ]
