# Generated by Django 5.2.1 on 2025-09-27 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Completo')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('asunto', models.CharField(choices=[('consulta', 'Consulta General'), ('consorcio', 'Consorcio Inmobiliario'), ('compra', 'Compra de Propiedad'), ('venta', 'Venta de Propiedad'), ('alquiler', 'Alquiler'), ('visita', 'Agendar Visita'), ('otro', 'Otro')], max_length=20, verbose_name='Asunto')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Envío')),
            ],
            options={
                'verbose_name': 'Envío de Contacto',
                'verbose_name_plural': 'Envíos de Contacto',
                'ordering': ['-fecha_envio'],
            },
        ),
    ]
