# Generated by Django 5.2.1 on 2025-09-27 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contactsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsubmission',
            name='fecha_entrada',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Entrada'),
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='fecha_salida',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Salida'),
        ),
    ]
