# Generated by Django 5.2.1 on 2025-09-27 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contactsubmission_fecha_entrada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsubmission',
            name='asunto',
            field=models.CharField(choices=[('alquiler', 'Alquiler')], max_length=20, verbose_name='Asunto'),
        ),
    ]
