# Generated by Django 5.2.1 on 2025-09-27 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_contactsubmission_asunto'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormularioCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_formulario', models.CharField(choices=[('contacto', 'Formulario de Contacto'), ('consulta_propiedad', 'Consulta de Propiedad'), ('cv', 'Formulario de CV')], max_length=20, verbose_name='Tipo de Formulario')),
                ('año', models.IntegerField(verbose_name='Año')),
                ('mes', models.IntegerField(verbose_name='Mes')),
                ('cantidad', models.PositiveIntegerField(default=0, verbose_name='Cantidad')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Conteo de Formulario',
                'verbose_name_plural': 'Conteos de Formularios',
                'ordering': ['-año', '-mes', 'tipo_formulario'],
                'unique_together': {('tipo_formulario', 'año', 'mes')},
            },
        ),
    ]
