# Generated by Django 5.2.1 on 2025-09-27 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_formulariocount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactsubmission',
            name='fecha_entrada',
        ),
        migrations.RemoveField(
            model_name='contactsubmission',
            name='fecha_salida',
        ),
    ]
