# Generated by Django 5.2.1 on 2025-09-29 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_contactsubmission_asunto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsubmission',
            name='asunto',
            field=models.CharField(choices=[('', 'Selecciona un asunto'), ('consulta_general', 'Consulta General'), ('alquiler', 'Alquiler'), ('alquiler_temporal', 'Alquiler Temporal'), ('venta', 'Venta'), ('consorcio', 'Consorcio'), ('tasacion', 'Tasación de Propiedad'), ('inversion', 'Inversión Inmobiliaria'), ('financiamiento', 'Financiamiento Hipotecario'), ('administracion', 'Administración de Propiedades'), ('legal', 'Asesoría Legal'), ('mantenimiento', 'Mantenimiento y Reparaciones'), ('seguros', 'Seguros Inmobiliarios'), ('otro', 'Otro')], max_length=30, verbose_name='Asunto'),
        ),
    ]
