# Generated by Django 5.2.1 on 2025-08-22 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo del Administrador')),
                ('password', models.CharField(max_length=128, verbose_name='Contraseña (encriptada)')),
                ('nombre_empresa', models.CharField(max_length=200, verbose_name='Nombre de la Empresa')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono de Contacto')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección de la Empresa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('activo', models.BooleanField(default=True, verbose_name='Credenciales Activas')),
            ],
            options={
                'verbose_name': 'Credenciales de Administrador',
                'verbose_name_plural': 'Credenciales de Administrador',
            },
        ),
    ]
