# Generated by Django 5.2.1 on 2025-08-23 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_remove_admincredentials_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admincredentials',
            name='apellido',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellido del Administrador'),
        ),
        migrations.AddField(
            model_name='admincredentials',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del Administrador'),
        ),
        migrations.AddField(
            model_name='admincredentials',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono del Administrador'),
        ),
    ]
