# Generated by Django 5.2.1 on 2025-08-23 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_admincredentials_apellido_admincredentials_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admincredentials',
            name='foto_perfil',
            field=models.ImageField(blank=True, help_text='Foto de perfil del administrador (opcional)', null=True, upload_to='admin_profiles/', verbose_name='Foto de Perfil'),
        ),
    ]
