# Generated by Django 5.2.1 on 2025-09-15 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_admincredentials_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='admincredentials',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, help_text='Fecha de nacimiento del administrador (opcional)', null=True, verbose_name='Fecha de Nacimiento'),
        ),
    ]
