# Generated by Django 5.2.1 on 2025-09-26 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_alter_admincredentials_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='admincredentials',
            name='backup_codes',
            field=models.JSONField(blank=True, default=list, verbose_name='Códigos de Respaldo'),
        ),
        migrations.AddField(
            model_name='admincredentials',
            name='totp_secret',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Clave Secreta TOTP'),
        ),
        migrations.AddField(
            model_name='admincredentials',
            name='two_factor_enabled',
            field=models.BooleanField(default=False, verbose_name='2FA Habilitado'),
        ),
    ]
