# Generated by Django 5.2.1 on 2025-09-26 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_admincredentials_backup_codes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('code', models.CharField(max_length=6, verbose_name='Código de Verificación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('used', models.BooleanField(default=False, verbose_name='Usado')),
                ('expires_at', models.DateTimeField(verbose_name='Fecha de Expiración')),
            ],
            options={
                'verbose_name': 'Código de Recuperación',
                'verbose_name_plural': 'Códigos de Recuperación',
                'ordering': ['-created_at'],
            },
        ),
    ]
