# Generated by Django 5.2.1 on 2026-08-23 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_passwordresetcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admincredentials',
            name='password',
        ),
    ]
