# Generated by Django 5.2.1 on 2025-08-22 00:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio')),
                ('tipo', models.CharField(choices=[('casa', 'Casa'), ('apartamento', 'Apartamento'), ('terreno', 'Terreno'), ('local', 'Local Comercial'), ('oficina', 'Oficina')], max_length=20, verbose_name='Tipo de Propiedad')),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('vendida', 'Vendida'), ('reservada', 'Reservada')], default='disponible', max_length=20, verbose_name='Estado')),
                ('ubicacion', models.CharField(max_length=300, verbose_name='Ubicación')),
                ('metros_cuadrados', models.PositiveIntegerField(verbose_name='Metros Cuadrados')),
                ('habitaciones', models.PositiveIntegerField(default=0, verbose_name='Habitaciones')),
                ('banos', models.PositiveIntegerField(default=0, verbose_name='Baños')),
                ('imagen_principal', models.ImageField(blank=True, null=True, upload_to='propiedades/', verbose_name='Imagen Principal')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Propiedad',
                'verbose_name_plural': 'Propiedades',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
