# Generated by Django 5.2.1 on 2025-08-23 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='operacion',
            field=models.CharField(choices=[('venta', 'Venta'), ('alquiler', 'Alquiler'), ('alquiler_temporal', 'Alquiler Temporal')], default='venta', max_length=20, verbose_name='Tipo de Operación'),
        ),
    ]
