# Generated by Django 5.2.1 on 2025-08-23 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_admincredentials_apellido_admincredentials_nombre_and_more'),
        ('propiedades', '0002_propiedad_operacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='administrador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.admincredentials', verbose_name='Administrador que creó la propiedad'),
        ),
    ]
