# Generated by Django 5.2.1 on 2025-08-28 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0003_propiedad_administrador'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='imagen_secundaria',
            field=models.ImageField(blank=True, null=True, upload_to='propiedades/', verbose_name='Imagen Secundaria'),
        ),
        migrations.CreateModel(
            name='FotoPropiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='propiedades/fotos/', verbose_name='Imagen')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción de la imagen')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden de la imagen')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='propiedades.propiedad', verbose_name='Propiedad')),
            ],
            options={
                'verbose_name': 'Foto de Propiedad',
                'verbose_name_plural': 'Fotos de Propiedades',
                'ordering': ['orden', 'fecha_subida'],
            },
        ),
    ]
