# Generated by Django 5.2.1 on 2025-09-16 02:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_alter_admincredentials_user'),
        ('propiedades', '0007_alter_clickpropiedad_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=100, verbose_name='Nombre del Usuario')),
                ('email_usuario', models.EmailField(max_length=254, verbose_name='Email del Usuario')),
                ('telefono_usuario', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono del Usuario')),
                ('calificacion', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Calificación (1-5 estrellas)')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título de la Reseña')),
                ('comentario', models.TextField(verbose_name='Comentario')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Aprobación'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20, verbose_name='Estado de la Reseña')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_moderacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Moderación')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('moderado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.admincredentials', verbose_name='Moderado por')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='propiedades.propiedad', verbose_name='Propiedad')),
            ],
            options={
                'verbose_name': 'Reseña',
                'verbose_name_plural': 'Reseñas',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
