# Generated by Django 5.2.1 on 2025-09-30 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0013_propiedad_ciudad_propiedad_lugares_cercanos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fotopropiedad',
            options={'ordering': ['orden', 'fecha_subida'], 'verbose_name': 'Foto/Video de Propiedad', 'verbose_name_plural': 'Fotos/Videos de Propiedades'},
        ),
        migrations.AddField(
            model_name='fotopropiedad',
            name='tipo_medio',
            field=models.CharField(choices=[('imagen', 'Imagen'), ('video', 'Video')], default='imagen', max_length=10, verbose_name='Tipo de Medio'),
        ),
        migrations.AddField(
            model_name='fotopropiedad',
            name='video',
            field=models.FileField(blank=True, help_text='Formatos soportados: MP4, WebM, AVI (máx. 200MB)', null=True, upload_to='propiedades/videos/', verbose_name='Video'),
        ),
        migrations.AlterField(
            model_name='fotopropiedad',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción del medio'),
        ),
        migrations.AlterField(
            model_name='fotopropiedad',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='propiedades/fotos/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='fotopropiedad',
            name='orden',
            field=models.PositiveIntegerField(default=0, verbose_name='Orden'),
        ),
    ]
