# Generated by Django 5.2.1 on 2025-10-08 02:59

import core.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0016_change_precio_decimal_places'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='ambientes',
            field=models.PositiveIntegerField(default=0, help_text='Número total de ambientes (incluye living, comedor, cocina, etc.)', verbose_name='Ambientes'),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='balcon',
            field=models.BooleanField(default=False, help_text='Indica si la propiedad cuenta con balcón', verbose_name='Tiene Balcón'),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True, verbose_name='URL amigable'),
        ),
        migrations.AlterField(
            model_name='fotopropiedad',
            name='imagen',
            field=core.fields.WebPImageField(blank=True, null=True, upload_to='propiedades/fotos/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='imagen_principal',
            field=core.fields.WebPImageField(blank=True, null=True, upload_to='propiedades/', verbose_name='Imagen Principal'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='imagen_secundaria',
            field=core.fields.WebPImageField(blank=True, null=True, upload_to='propiedades/', verbose_name='Imagen Secundaria'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio'),
        ),
    ]
