# Generated by Django 5.2.1 on 2025-10-07 03:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0016_change_precio_decimal_places'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=False, verbose_name='URL amigable'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio'),
        ),
    ]
