# Generated by Django 5.2.1 on 2025-10-07 03:57

from django.db import migrations
from django.utils.text import slugify


def generate_slugs(apps, schema_editor):
    """Generar slugs únicos para todas las propiedades"""
    Propiedad = apps.get_model('propiedades', 'Propiedad')
    
    for propiedad in Propiedad.objects.all():
        base_slug = slugify(propiedad.titulo)
        slug = base_slug
        counter = 1
        
        # Asegurar que el slug sea único
        while Propiedad.objects.filter(slug=slug).exclude(id=propiedad.id).exists():
            slug = f"{base_slug}-{counter}"
            counter += 1
        
        propiedad.slug = slug
        propiedad.save()


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0017_propiedad_slug_alter_propiedad_precio'),
    ]

    operations = [
        migrations.RunPython(generate_slugs),
    ]
