# Generated by Django 5.2.1 on 2025-10-07 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0017_alter_propiedad_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True, verbose_name='URL amigable'),
        ),
    ]
