# Generated by Django 5.2.1 on 2025-10-07 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0018_auto_20251007_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True, verbose_name='URL amigable'),
        ),
    ]
