# Generated by Django 5.2.1 on 2025-10-08 02:49

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0019_propiedad_ambientes_propiedad_balcon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotopropiedad',
            name='imagen',
            field=core.fields.WebPImageField(blank=True, null=True, upload_to='propiedades/fotos/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='imagen_principal',
            field=core.fields.WebPImageField(blank=True, null=True, upload_to='propiedades/', verbose_name='Imagen Principal'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='imagen_secundaria',
            field=core.fields.WebPImageField(blank=True, null=True, upload_to='propiedades/', verbose_name='Imagen Secundaria'),
        ),
    ]
