# Generated by Django 5.2.1 on 2025-10-07 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0019_auto_20251007_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='ambientes',
            field=models.PositiveIntegerField(default=0, help_text='Número total de ambientes (incluye living, comedor, cocina, etc.)', verbose_name='Ambientes'),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='balcon',
            field=models.BooleanField(default=False, help_text='Indica si la propiedad cuenta con balcón', verbose_name='Tiene Balcón'),
        ),
    ]
