# Generated by Django 5.2.1 on 2025-10-08 02:44

from django.db import migrations
import core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0018_auto_20251007_0057'),  # Dependencia más segura
    ]

    operations = [
        migrations.AlterField(
            model_name='fotopropiedad',
            name='imagen',
            field=core.fields.WebPImageField(blank=True, null=True, upload_to='propiedades/fotos/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='imagen_principal',
            field=core.fields.WebPImageField(blank=True, null=True, upload_to='propiedades/', verbose_name='Imagen Principal'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='imagen_secundaria',
            field=core.fields.WebPImageField(blank=True, null=True, upload_to='propiedades/', verbose_name='Imagen Secundaria'),
        ),
    ]
