<<<<<<< HEAD:propiedades/migrations/0020_alter_fotopropiedad_imagen_and_more.py
# Generated by Django 5.2.1 on 2025-10-08 02:49

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0019_propiedad_ambientes_propiedad_balcon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotopropiedad',
            name='imagen',
            field=core.fields.WebPImageField(blank=True, null=True, upload_to='propiedades/fotos/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='imagen_principal',
            field=core.fields.WebPImageField(blank=True, null=True, upload_to='propiedades/', verbose_name='Imagen Principal'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='imagen_secundaria',
            field=core.fields.WebPImageField(blank=True, null=True, upload_to='propiedades/', verbose_name='Imagen Secundaria'),
        ),
    ]
=======
# Generated by Django 5.2.1 on 2025-10-08 02:44

from django.db import migrations
import core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0018_auto_20251007_0057'),  # Dependencia más segura
    ]

    operations = [
        migrations.AlterField(
            model_name='fotopropiedad',
            name='imagen',
            field=core.fields.WebPImageField(blank=True, null=True, upload_to='propiedades/fotos/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='imagen_principal',
            field=core.fields.WebPImageField(blank=True, null=True, upload_to='propiedades/', verbose_name='Imagen Principal'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='imagen_secundaria',
            field=core.fields.WebPImageField(blank=True, null=True, upload_to='propiedades/', verbose_name='Imagen Secundaria'),
        ),
    ]
>>>>>>> 1b5f64dc1d1ff6ceb8e05807eeadbc4bf538e585:propiedades/migrations/0021_fix_webp_fields.py
