# Generated by Django 5.2.1 on 2025-10-08 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0019_propiedad_ambientes_propiedad_balcon_and_more'),
        ('propiedades', '0021_fix_webp_fields'),
    ]

    operations = [
    ]
