# Generated by Django 5.2.1 on 2025-08-28 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0004_propiedad_imagen_secundaria_fotopropiedad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('icono', models.CharField(help_text='Clase de Font Awesome (ej: fa-swimming-pool)', max_length=50)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Amenidad',
                'verbose_name_plural': 'Amenidades',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='propiedad',
            name='amenidades',
            field=models.ManyToManyField(blank=True, to='propiedades.amenidad', verbose_name='Amenidades incluidas'),
        ),
    ]
