# Generated by Django 5.2.1 on 2025-09-15 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0005_amenidad_propiedad_amenidades'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickPropiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuente', models.CharField(choices=[('home', 'Página de Inicio'), ('buscar', 'Página de Búsqueda'), ('otro', 'Otra Página')], max_length=20, verbose_name='Fuente del clic')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('fecha_click', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del Clic')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='propiedades.propiedad', verbose_name='Propiedad')),
            ],
            options={
                'verbose_name': 'Clic en Propiedad',
                'verbose_name_plural': 'Clics en Propiedades',
                'ordering': ['-fecha_click'],
                'indexes': [models.Index(fields=['propiedad', 'fecha_click'], name='propiedades_propied_c329ab_idx'), models.Index(fields=['fuente', 'fecha_click'], name='propiedades_fuente_0713b3_idx')],
            },
        ),
    ]
