# Generated by Django 5.2.1 on 2025-09-15 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0006_clickpropiedad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clickpropiedad',
            options={'ordering': ['-fecha_click'], 'verbose_name': 'Click en Propiedad', 'verbose_name_plural': 'Clicks en Propiedades'},
        ),
        migrations.RemoveIndex(
            model_name='clickpropiedad',
            name='propiedades_propied_c329ab_idx',
        ),
        migrations.RemoveIndex(
            model_name='clickpropiedad',
            name='propiedades_fuente_0713b3_idx',
        ),
        migrations.RemoveField(
            model_name='clickpropiedad',
            name='fuente',
        ),
        migrations.AddField(
            model_name='clickpropiedad',
            name='pagina_origen',
            field=models.CharField(choices=[('home', 'Página de Inicio'), ('buscar', 'Página de Búsqueda'), ('detalle', 'Página de Detalle'), ('otra', 'Otra Página')], default='home', max_length=100, verbose_name='Página de Origen'),
        ),
        migrations.AlterField(
            model_name='clickpropiedad',
            name='fecha_click',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha del Click'),
        ),
    ]
