# Generated by Django 5.2.1 on 2025-09-27 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0010_alter_propiedad_latitud_alter_propiedad_longitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Coordenada de latitud (ej: -38.9516)', max_digits=10, null=True, verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Coordenada de longitud (ej: -68.0591)', max_digits=10, null=True, verbose_name='Longitud'),
        ),
    ]
