# Generated by Django 5.2.1 on 2025-09-29 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0011_alter_propiedad_latitud_alter_propiedad_longitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=15, help_text='Coordenada de latitud (ej: -33.6914783645518)', max_digits=20, null=True, verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=15, help_text='Coordenada de longitud (ej: -65.45524318970048)', max_digits=20, null=True, verbose_name='Longitud'),
        ),
    ]
