# Generated by Django 5.2.1 on 2025-09-29 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0012_alter_propiedad_latitud_alter_propiedad_longitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='lugares_cercanos',
            field=models.TextField(blank=True, help_text='Describe los lugares cercanos como centros comerciales, restaurantes, servicios, etc.', null=True, verbose_name='Lugares Cercanos'),
        ),
    ]
