# Generated by Django 5.2.1 on 2025-09-30 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0014_alter_fotopropiedad_options_fotopropiedad_tipo_medio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotopropiedad',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción del archivo'),
        ),
        migrations.AlterField(
            model_name='fotopropiedad',
            name='orden',
            field=models.PositiveIntegerField(default=0, verbose_name='Orden del archivo'),
        ),
        migrations.AlterField(
            model_name='fotopropiedad',
            name='video',
            field=models.FileField(blank=True, help_text='Formato de video (MP4, AVI, MOV)', null=True, upload_to='propiedades/videos/', verbose_name='Video'),
        ),
    ]
